version: "3.2"

services:
  postgres:
    image: postgres
    container_name: finance_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    volumes:
      - $PWD/dev-tools/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"